# Generated by Django 5.0.3 on 2024-07-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201126_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='created_at',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='updated_at',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_name',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
    ]
